import type { Equipment } from "@shared/schema";

export const equipmentDatabase: Equipment[] = [
  // Furnaces
  {
    id: "carrier-59mn7a080",
    manufacturer: "Carrier",
    model: "59MN7A080V21-16",
    price: 1450,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalBtu: 80000,
    heatingCapacityBtu: 73600,
    afue: 0.92,
    nominalTons: undefined,
    coolingCapacityBtu: undefined,
    seer: undefined,
    hspf: undefined,
    latentCoolingBtu: undefined,
    cabinetWidth: 17.5,
    cabinetHeight: 33,
    cabinetDepth: 29,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
  },
  {
    id: "trane-xv95",
    manufacturer: "Trane",
    model: "XV95 TUD1C080A9421A",
    price: 1850,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalBtu: 80000,
    heatingCapacityBtu: 76800,
    afue: 0.96,
    nominalTons: undefined,
    coolingCapacityBtu: undefined,
    seer: undefined,
    hspf: undefined,
    latentCoolingBtu: undefined,
    cabinetWidth: 17.5,
    cabinetHeight: 33,
    cabinetDepth: 28.5,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
  },
  {
    id: "lennox-ml195",
    manufacturer: "Lennox",
    model: "ML195UH090XE48C",
    price: 1675,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalBtu: 90000,
    heatingCapacityBtu: 85500,
    afue: 0.95,
    nominalTons: undefined,
    coolingCapacityBtu: undefined,
    seer: undefined,
    hspf: undefined,
    latentCoolingBtu: undefined,
    cabinetWidth: 24.5,
    cabinetHeight: 33,
    cabinetDepth: 28.5,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
  },
  {
    id: "rheem-r95ta",
    manufacturer: "Rheem",
    model: "R95TA0751524MSA",
    price: 1225,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalBtu: 75000,
    heatingCapacityBtu: 60000,
    afue: 0.80,
    nominalTons: undefined,
    coolingCapacityBtu: undefined,
    seer: undefined,
    hspf: undefined,
    latentCoolingBtu: undefined,
    cabinetWidth: 17.5,
    cabinetHeight: 33,
    cabinetDepth: 29,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
  },
  {
    id: "goodman-gmss96",
    manufacturer: "Goodman",
    model: "GMSS960603BN",
    price: 985,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalBtu: 60000,
    heatingCapacityBtu: 57600,
    afue: 0.96,
    nominalTons: undefined,
    coolingCapacityBtu: undefined,
    seer: undefined,
    hspf: undefined,
    latentCoolingBtu: undefined,
    cabinetWidth: 17.5,
    cabinetHeight: 33,
    cabinetDepth: 29,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
  },

  // Air Conditioners
  {
    id: "carrier-25hcb3",
    manufacturer: "Carrier",
    model: "25HCB336A003",
    price: 1850,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 3.0,
    coolingCapacityBtu: 36000,
    seer: 14.5,
    latentCoolingBtu: 10800,
    nominalBtu: undefined,
    heatingCapacityBtu: undefined,
    afue: undefined,
    hspf: undefined,
    cabinetWidth: 35.4,
    cabinetHeight: 31.0,
    cabinetDepth: 35.4,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
  },
  {
    id: "trane-4ttr3",
    manufacturer: "Trane",
    model: "4TTR3036A1000AA",
    price: 2150,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 3.0,
    coolingCapacityBtu: 36000,
    seer: 16.0,
    latentCoolingBtu: 10800,
    nominalBtu: undefined,
    heatingCapacityBtu: undefined,
    afue: undefined,
    hspf: undefined,
    cabinetWidth: 34.8,
    cabinetHeight: 31.0,
    cabinetDepth: 34.8,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
  },
  {
    id: "lennox-xc25",
    manufacturer: "Lennox",
    model: "XC25-048-230",
    price: 2750,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 4.0,
    coolingCapacityBtu: 48000,
    seer: 26.0,
    latentCoolingBtu: 14400,
    nominalBtu: undefined,
    heatingCapacityBtu: undefined,
    afue: undefined,
    hspf: undefined,
    cabinetWidth: 35.4,
    cabinetHeight: 31.0,
    cabinetDepth: 35.4,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
  },
  {
    id: "rheem-ra20",
    manufacturer: "Rheem",
    model: "RA2024AJ1NA",
    price: 1425,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 2.0,
    coolingCapacityBtu: 24000,
    seer: 13.0,
    latentCoolingBtu: 7200,
    nominalBtu: undefined,
    heatingCapacityBtu: undefined,
    afue: undefined,
    hspf: undefined,
    cabinetWidth: 29.0,
    cabinetHeight: 31.0,
    cabinetDepth: 29.0,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
  },

  // Heat Pumps
  {
    id: "carrier-25hpa5",
    manufacturer: "Carrier",
    model: "25HPA536A003",
    price: 2850,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "heating_cooling",
    nominalTons: 3.0,
    coolingCapacityBtu: 36000,
    heatingCapacityBtu: 31000,
    seer: 16.0,
    hspf: 9.0,
    latentCoolingBtu: 10800,
    nominalBtu: undefined,
    afue: undefined,
    cabinetWidth: 35.4,
    cabinetHeight: 31.0,
    cabinetDepth: 35.4,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
  },
  {
    id: "trane-4twp4",
    manufacturer: "Trane",
    model: "4TWP4036A1000AA",
    price: 3150,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "heating_cooling",
    nominalTons: 3.0,
    coolingCapacityBtu: 36000,
    heatingCapacityBtu: 32000,
    seer: 17.0,
    hspf: 9.5,
    latentCoolingBtu: 10800,
    nominalBtu: undefined,
    afue: undefined,
    cabinetWidth: 34.8,
    cabinetHeight: 31.0,
    cabinetDepth: 34.8,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
  },
  {
    id: "lennox-xp25",
    manufacturer: "Lennox",
    model: "XP25-048-230",
    price: 4850,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "outdoor",
    systemFunction: "heating_cooling",
    nominalTons: 4.0,
    coolingCapacityBtu: 48000,
    heatingCapacityBtu: 47000,
    seer: 23.5,
    hspf: 10.2,
    latentCoolingBtu: 14400,
    nominalBtu: undefined,
    afue: undefined,
    cabinetWidth: 35.4,
    cabinetHeight: 31.0,
    cabinetDepth: 35.4,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
  },
  {
    id: "rheem-rp20",
    manufacturer: "Rheem",
    model: "RP2042AJ1NA",
    price: 2650,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "heating_cooling",
    nominalTons: 3.5,
    coolingCapacityBtu: 42000,
    heatingCapacityBtu: 36000,
    seer: 14.5,
    hspf: 8.5,
    latentCoolingBtu: 12600,
    nominalBtu: undefined,
    afue: undefined,
    cabinetWidth: 35.4,
    cabinetHeight: 31.0,
    cabinetDepth: 35.4,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
  },
  {
    id: "goodman-gszc18",
    manufacturer: "Goodman",
    model: "GSZC180481",
    price: 2450,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "heating_cooling",
    nominalTons: 4.0,
    coolingCapacityBtu: 48000,
    heatingCapacityBtu: 42000,
    seer: 18.0,
    hspf: 10.0,
    latentCoolingBtu: 14400,
    nominalBtu: undefined,
    afue: undefined,
    cabinetWidth: 35.4,
    cabinetHeight: 31.0,
    cabinetDepth: 35.4,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
  },
  {
    id: "american-standard-4a7a4",
    manufacturer: "American Standard",
    model: "4A7A4048A1000AA",
    price: 2950,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "heating_cooling",
    nominalTons: 4.0,
    coolingCapacityBtu: 48000,
    heatingCapacityBtu: 43000,
    seer: 16.0,
    hspf: 9.0,
    latentCoolingBtu: 14400,
    nominalBtu: undefined,
    afue: undefined,
    cabinetWidth: 34.8,
    cabinetHeight: 31.0,
    cabinetDepth: 34.8,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
  },

  // Mini-Split Heat Pumps
  {
    id: "mitsubishi-mszfh18na",
    manufacturer: "Mitsubishi",
    model: "MSZ-FH18NA",
    price: 3200,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ductless",
    staging: "variable_speed",
    unitLocation: "outdoor",
    systemFunction: "heating_cooling",
    nominalTons: 1.5,
    coolingCapacityBtu: 18000,
    heatingCapacityBtu: 19000,
    seer: 33.1,
    hspf: 15.0,
    latentCoolingBtu: 5400,
    nominalBtu: undefined,
    afue: undefined,
    cabinetWidth: 31.5,
    cabinetHeight: 21.6,
    cabinetDepth: 11.8,
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?ixlib=rb-4.0.3&auto=format&fit=crop&w=300&h=200",
  }
];