import type { Equipment } from "@shared/schema";

export const equipmentDatabase: Equipment[] = [
  // AMERICAN STANDARD FURNACES
  {
    id: "american-standard-s9v2-40000-single",
    manufacturer: "American Standard",
    model: "S9V2-40000",
    price: 2368,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 40000,
    heatingCapacityBtu: 32000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.8,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/gas-furnaces/s9v2/S9V2-gas-furnace-cutaway.jpg"
  },
  {
    id: "american-standard-s9v2-40000-two",
    manufacturer: "American Standard",
    model: "S9V2-40000",
    price: 2590,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 40000,
    heatingCapacityBtu: 32000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.8,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/gas-furnaces/s9v2/S9V2-gas-furnace-cutaway.jpg"
  },
  {
    id: "american-standard-s9v2-40000-variable",
    manufacturer: "American Standard",
    model: "S9V2-40000",
    price: 2469,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 40000,
    heatingCapacityBtu: 32000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.8,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/gas-furnaces/s9v2/S9V2-gas-furnace-cutaway.jpg"
  },
  {
    id: "american-standard-s8v2-50000-single",
    manufacturer: "American Standard",
    model: "S8V2-50000",
    price: 3022,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 50000,
    heatingCapacityBtu: 46000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.92,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/gas-furnaces/s8v2/S8V2-Gas-Furnace-Cutaway.jpg"
  },
  {
    id: "american-standard-s8v2-50000-two",
    manufacturer: "American Standard",
    model: "S8V2-50000",
    price: 3029,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 50000,
    heatingCapacityBtu: 46000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.92,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/gas-furnaces/s8v2/S8V2-Gas-Furnace-Cutaway.jpg"
  },
  {
    id: "american-standard-s8v2-50000-variable",
    manufacturer: "American Standard",
    model: "S8V2-50000",
    price: 3300,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 50000,
    heatingCapacityBtu: 46000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.92,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/gas-furnaces/s8v2/S8V2-Gas-Furnace-Cutaway.jpg"
  },
  {
    id: "american-standard-s8x2-60000-single",
    manufacturer: "American Standard",
    model: "S8X2-60000",
    price: 3991,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 60000,
    heatingCapacityBtu: 57600,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.96,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/gas-furnaces/s8x2/S8X2-Gas-Furnace-Cutaway.jpg"
  },
  {
    id: "american-standard-s8x2-60000-two",
    manufacturer: "American Standard",
    model: "S8X2-60000",
    price: 3768,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 60000,
    heatingCapacityBtu: 57600,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.96,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/gas-furnaces/s8x2/S8X2-Gas-Furnace-Cutaway.jpg"
  },
  {
    id: "american-standard-s8x2-60000-variable",
    manufacturer: "American Standard",
    model: "S8X2-60000",
    price: 3644,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 60000,
    heatingCapacityBtu: 57600,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.96,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/gas-furnaces/s8x2/S8X2-Gas-Furnace-Cutaway.jpg"
  },
  {
    id: "american-standard-s9v2-80000-single",
    manufacturer: "American Standard",
    model: "S9V2-80000",
    price: 4388,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 80000,
    heatingCapacityBtu: 77600,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.97,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/gas-furnaces/s9v2/S9V2-gas-furnace-cutaway.jpg"
  },
  {
    id: "american-standard-s9v2-80000-two",
    manufacturer: "American Standard",
    model: "S9V2-80000",
    price: 4497,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 80000,
    heatingCapacityBtu: 77600,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.97,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/gas-furnaces/s9v2/S9V2-gas-furnace-cutaway.jpg"
  },
  {
    id: "american-standard-s9v2-80000-variable",
    manufacturer: "American Standard",
    model: "S9V2-80000",
    price: 4338,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 80000,
    heatingCapacityBtu: 77600,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.97,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/gas-furnaces/s9v2/S9V2-gas-furnace-cutaway.jpg"
  },
  {
    id: "american-standard-s8v2-100000-single",
    manufacturer: "American Standard",
    model: "S8V2-100000",
    price: 5233,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 100000,
    heatingCapacityBtu: 98000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.98,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/gas-furnaces/s8v2/S8V2-Gas-Furnace-Cutaway.jpg"
  },
  {
    id: "american-standard-s8v2-100000-two",
    manufacturer: "American Standard",
    model: "S8V2-100000",
    price: 5392,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 100000,
    heatingCapacityBtu: 98000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.98,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/gas-furnaces/s8v2/S8V2-Gas-Furnace-Cutaway.jpg"
  },
  {
    id: "american-standard-s8v2-100000-variable",
    manufacturer: "American Standard",
    model: "S8V2-100000",
    price: 5044,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 100000,
    heatingCapacityBtu: 98000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.98,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/gas-furnaces/s8v2/S8V2-Gas-Furnace-Cutaway.jpg"
  },
  {
    id: "american-standard-s8x2-120000-single",
    manufacturer: "American Standard",
    model: "S8X2-120000",
    price: 5846,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 120000,
    heatingCapacityBtu: 96000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.8,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/gas-furnaces/s8x2/S8X2-Gas-Furnace-Cutaway.jpg"
  },
  {
    id: "american-standard-s8x2-120000-two",
    manufacturer: "American Standard",
    model: "S8X2-120000",
    price: 5811,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 120000,
    heatingCapacityBtu: 96000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.8,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/gas-furnaces/s8x2/S8X2-Gas-Furnace-Cutaway.jpg"
  },
  {
    id: "american-standard-s8x2-120000-variable",
    manufacturer: "American Standard",
    model: "S8X2-120000",
    price: 6013,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 120000,
    heatingCapacityBtu: 96000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.8,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/gas-furnaces/s8x2/S8X2-Gas-Furnace-Cutaway.jpg"
  },

  // AMERICAN STANDARD AIR CONDITIONERS
  {
    id: "american-standard-4ac16015-single",
    manufacturer: "American Standard",
    model: "4AC16015",
    price: 2747,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 1.5,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 18000,
    latentCoolingBtu: 5940,
    afue: null,
    seer: 14,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/air-conditioners/4ac16/4AC16-Air-Conditioner.jpg"
  },
  {
    id: "american-standard-4ac16015-two",
    manufacturer: "American Standard",
    model: "4AC16015",
    price: 2738,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 1.5,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 18000,
    latentCoolingBtu: 5940,
    afue: null,
    seer: 14,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/air-conditioners/4ac16/4AC16-Air-Conditioner.jpg"
  },
  {
    id: "american-standard-4ac16015-variable",
    manufacturer: "American Standard",
    model: "4AC16015",
    price: 2865,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 1.5,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 18000,
    latentCoolingBtu: 5940,
    afue: null,
    seer: 14,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/air-conditioners/4ac16/4AC16-Air-Conditioner.jpg"
  },
  {
    id: "american-standard-4ac14020-single",
    manufacturer: "American Standard",
    model: "4AC14020",
    price: 3545,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 2,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 24000,
    latentCoolingBtu: 7920,
    afue: null,
    seer: 15,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/air-conditioners/4ac14/4AC14-Air-Conditioner.jpg"
  },
  {
    id: "american-standard-4ac14020-two",
    manufacturer: "American Standard",
    model: "4AC14020",
    price: 3419,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 2,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 24000,
    latentCoolingBtu: 7920,
    afue: null,
    seer: 15,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/air-conditioners/4ac14/4AC14-Air-Conditioner.jpg"
  },
  {
    id: "american-standard-4ac14020-variable",
    manufacturer: "American Standard",
    model: "4AC14020",
    price: 3397,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 2,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 24000,
    latentCoolingBtu: 7920,
    afue: null,
    seer: 15,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/air-conditioners/4ac14/4AC14-Air-Conditioner.jpg"
  },
  {
    id: "american-standard-4ac13025-single",
    manufacturer: "American Standard",
    model: "4AC13025",
    price: 3919,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 2.5,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 30000,
    latentCoolingBtu: 9900,
    afue: null,
    seer: 16,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/air-conditioners/4ac13/4AC13-Air-Conditioner.jpg"
  },
  {
    id: "american-standard-4ac13025-two",
    manufacturer: "American Standard",
    model: "4AC13025",
    price: 3922,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 2.5,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 30000,
    latentCoolingBtu: 9900,
    afue: null,
    seer: 16,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/air-conditioners/4ac13/4AC13-Air-Conditioner.jpg"
  },
  {
    id: "american-standard-4ac13025-variable",
    manufacturer: "American Standard",
    model: "4AC13025",
    price: 4063,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 2.5,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 30000,
    latentCoolingBtu: 9900,
    afue: null,
    seer: 16,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/air-conditioners/4ac13/4AC13-Air-Conditioner.jpg"
  },
  {
    id: "american-standard-4ac16030-single",
    manufacturer: "American Standard",
    model: "4AC16030",
    price: 4943,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 3,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 36000,
    latentCoolingBtu: 11880,
    afue: null,
    seer: 17,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/air-conditioners/4ac16/4AC16-Air-Conditioner.jpg"
  },
  {
    id: "american-standard-4ac16030-two",
    manufacturer: "American Standard",
    model: "4AC16030",
    price: 4782,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 3,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 36000,
    latentCoolingBtu: 11880,
    afue: null,
    seer: 17,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/air-conditioners/4ac16/4AC16-Air-Conditioner.jpg"
  },
  {
    id: "american-standard-4ac16030-variable",
    manufacturer: "American Standard",
    model: "4AC16030",
    price: 4675,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 3,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 36000,
    latentCoolingBtu: 11880,
    afue: null,
    seer: 17,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/air-conditioners/4ac16/4AC16-Air-Conditioner.jpg"
  },
  {
    id: "american-standard-4ac14040-single",
    manufacturer: "American Standard",
    model: "4AC14040",
    price: 6028,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 4,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 48000,
    latentCoolingBtu: 15840,
    afue: null,
    seer: 18,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/air-conditioners/4ac14/4AC14-Air-Conditioner.jpg"
  },
  {
    id: "american-standard-4ac14040-two",
    manufacturer: "American Standard",
    model: "4AC14040",
    price: 6008,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 4,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 48000,
    latentCoolingBtu: 15840,
    afue: null,
    seer: 18,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/air-conditioners/4ac14/4AC14-Air-Conditioner.jpg"
  },
  {
    id: "american-standard-4ac14040-variable",
    manufacturer: "American Standard",
    model: "4AC14040",
    price: 6176,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 4,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 48000,
    latentCoolingBtu: 15840,
    afue: null,
    seer: 18,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/air-conditioners/4ac14/4AC14-Air-Conditioner.jpg"
  },
  {
    id: "american-standard-4ac13050-single",
    manufacturer: "American Standard",
    model: "4AC13050",
    price: 7450,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 5,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 60000,
    latentCoolingBtu: 19800,
    afue: null,
    seer: 20,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/air-conditioners/4ac13/4AC13-Air-Conditioner.jpg"
  },
  {
    id: "american-standard-4ac13050-two",
    manufacturer: "American Standard",
    model: "4AC13050",
    price: 7627,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 5,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 60000,
    latentCoolingBtu: 19800,
    afue: null,
    seer: 20,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/air-conditioners/4ac13/4AC13-Air-Conditioner.jpg"
  },
  {
    id: "american-standard-4ac13050-variable",
    manufacturer: "American Standard",
    model: "4AC13050",
    price: 7317,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 5,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 60000,
    latentCoolingBtu: 19800,
    afue: null,
    seer: 20,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/air-conditioners/4ac13/4AC13-Air-Conditioner.jpg"
  },

  // AMERICAN STANDARD HEAT PUMPS
  {
    id: "american-standard-4txd015-single",
    manufacturer: "American Standard",
    model: "4TXD015",
    price: 3148,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 1.5,
    nominalBtu: null,
    heatingCapacityBtu: 16560,
    coolingCapacityBtu: 18000,
    latentCoolingBtu: 5940,
    afue: null,
    seer: 14,
    hspf: 8.2,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/heat-pumps/4txd/4TXD-Heat-Pump.jpg"
  },
  {
    id: "american-standard-4txd015-two",
    manufacturer: "American Standard",
    model: "4TXD015",
    price: 3019,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 1.5,
    nominalBtu: null,
    heatingCapacityBtu: 16560,
    coolingCapacityBtu: 18000,
    latentCoolingBtu: 5940,
    afue: null,
    seer: 14,
    hspf: 8.2,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/heat-pumps/4txd/4TXD-Heat-Pump.jpg"
  },
  {
    id: "american-standard-4txd015-variable",
    manufacturer: "American Standard",
    model: "4TXD015",
    price: 3141,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 1.5,
    nominalBtu: null,
    heatingCapacityBtu: 16560,
    coolingCapacityBtu: 18000,
    latentCoolingBtu: 5940,
    afue: null,
    seer: 14,
    hspf: 8.2,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/heat-pumps/4txd/4TXD-Heat-Pump.jpg"
  },
  {
    id: "american-standard-4twd020-single",
    manufacturer: "American Standard",
    model: "4TWD020",
    price: 3805,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 2,
    nominalBtu: null,
    heatingCapacityBtu: 22080,
    coolingCapacityBtu: 24000,
    latentCoolingBtu: 7920,
    afue: null,
    seer: 15,
    hspf: 8.5,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/heat-pumps/4twd/4TWD-Heat-Pump.jpg"
  },
  {
    id: "american-standard-4twd020-two",
    manufacturer: "American Standard",
    model: "4TWD020",
    price: 4012,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 2,
    nominalBtu: null,
    heatingCapacityBtu: 22080,
    coolingCapacityBtu: 24000,
    latentCoolingBtu: 7920,
    afue: null,
    seer: 15,
    hspf: 8.5,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/heat-pumps/4twd/4TWD-Heat-Pump.jpg"
  },
  {
    id: "american-standard-4twd020-variable",
    manufacturer: "American Standard",
    model: "4TWD020",
    price: 3973,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 2,
    nominalBtu: null,
    heatingCapacityBtu: 22080,
    coolingCapacityBtu: 24000,
    latentCoolingBtu: 7920,
    afue: null,
    seer: 15,
    hspf: 8.5,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/heat-pumps/4twd/4TWD-Heat-Pump.jpg"
  },
  {
    id: "american-standard-4txa025-single",
    manufacturer: "American Standard",
    model: "4TXA025",
    price: 4632,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 2.5,
    nominalBtu: null,
    heatingCapacityBtu: 27600,
    coolingCapacityBtu: 30000,
    latentCoolingBtu: 9900,
    afue: null,
    seer: 16,
    hspf: 9,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/heat-pumps/4txa/4TXA-Heat-Pump.jpg"
  },
  {
    id: "american-standard-4txa025-two",
    manufacturer: "American Standard",
    model: "4TXA025",
    price: 4687,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 2.5,
    nominalBtu: null,
    heatingCapacityBtu: 27600,
    coolingCapacityBtu: 30000,
    latentCoolingBtu: 9900,
    afue: null,
    seer: 16,
    hspf: 9,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/heat-pumps/4txa/4TXA-Heat-Pump.jpg"
  },
  {
    id: "american-standard-4txa025-variable",
    manufacturer: "American Standard",
    model: "4TXA025",
    price: 4653,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 2.5,
    nominalBtu: null,
    heatingCapacityBtu: 27600,
    coolingCapacityBtu: 30000,
    latentCoolingBtu: 9900,
    afue: null,
    seer: 16,
    hspf: 9,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/heat-pumps/4txa/4TXA-Heat-Pump.jpg"
  },
  {
    id: "american-standard-4txd030-single",
    manufacturer: "American Standard",
    model: "4TXD030",
    price: 5214,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 3,
    nominalBtu: null,
    heatingCapacityBtu: 33120,
    coolingCapacityBtu: 36000,
    latentCoolingBtu: 11880,
    afue: null,
    seer: 17,
    hspf: 9.5,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/heat-pumps/4txd/4TXD-Heat-Pump.jpg"
  },
  {
    id: "american-standard-4txd030-two",
    manufacturer: "American Standard",
    model: "4TXD030",
    price: 5375,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 3,
    nominalBtu: null,
    heatingCapacityBtu: 33120,
    coolingCapacityBtu: 36000,
    latentCoolingBtu: 11880,
    afue: null,
    seer: 17,
    hspf: 9.5,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/heat-pumps/4txd/4TXD-Heat-Pump.jpg"
  },
  {
    id: "american-standard-4txd030-variable",
    manufacturer: "American Standard",
    model: "4TXD030",
    price: 5229,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 3,
    nominalBtu: null,
    heatingCapacityBtu: 33120,
    coolingCapacityBtu: 36000,
    latentCoolingBtu: 11880,
    afue: null,
    seer: 17,
    hspf: 9.5,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/heat-pumps/4txd/4TXD-Heat-Pump.jpg"
  },
  {
    id: "american-standard-4twd040-single",
    manufacturer: "American Standard",
    model: "4TWD040",
    price: 6742,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 4,
    nominalBtu: null,
    heatingCapacityBtu: 44160,
    coolingCapacityBtu: 48000,
    latentCoolingBtu: 15840,
    afue: null,
    seer: 18,
    hspf: 10,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/heat-pumps/4twd/4TWD-Heat-Pump.jpg"
  },
  {
    id: "american-standard-4twd040-two",
    manufacturer: "American Standard",
    model: "4TWD040",
    price: 6810,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 4,
    nominalBtu: null,
    heatingCapacityBtu: 44160,
    coolingCapacityBtu: 48000,
    latentCoolingBtu: 15840,
    afue: null,
    seer: 18,
    hspf: 10,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/heat-pumps/4twd/4TWD-Heat-Pump.jpg"
  },
  {
    id: "american-standard-4twd040-variable",
    manufacturer: "American Standard",
    model: "4TWD040",
    price: 6862,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 4,
    nominalBtu: null,
    heatingCapacityBtu: 44160,
    coolingCapacityBtu: 48000,
    latentCoolingBtu: 15840,
    afue: null,
    seer: 18,
    hspf: 10,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/heat-pumps/4twd/4TWD-Heat-Pump.jpg"
  },
  {
    id: "american-standard-4txa050-single",
    manufacturer: "American Standard",
    model: "4TXA050",
    price: 8275,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 5,
    nominalBtu: null,
    heatingCapacityBtu: 55200,
    coolingCapacityBtu: 60000,
    latentCoolingBtu: 19800,
    afue: null,
    seer: 20,
    hspf: 10.5,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/heat-pumps/4txa/4TXA-Heat-Pump.jpg"
  },
  {
    id: "american-standard-4txa050-two",
    manufacturer: "American Standard",
    model: "4TXA050",
    price: 8173,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 5,
    nominalBtu: null,
    heatingCapacityBtu: 55200,
    coolingCapacityBtu: 60000,
    latentCoolingBtu: 19800,
    afue: null,
    seer: 20,
    hspf: 10.5,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/heat-pumps/4txa/4TXA-Heat-Pump.jpg"
  },
  {
    id: "american-standard-4txa050-variable",
    manufacturer: "American Standard",
    model: "4TXA050",
    price: 8068,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 5,
    nominalBtu: null,
    heatingCapacityBtu: 55200,
    coolingCapacityBtu: 60000,
    latentCoolingBtu: 19800,
    afue: null,
    seer: 20,
    hspf: 10.5,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.americanstandardair.com/content/dam/as-air/na/us/products/heat-pumps/4txa/4TXA-Heat-Pump.jpg"
  },

  // RHEEM FURNACES
  {
    id: "rheem-r96v-40000-single",
    manufacturer: "Rheem",
    model: "R96V-40000",
    price: 2319,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 40000,
    heatingCapacityBtu: 32000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.8,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/gas-furnaces/r96v/R96V-Prestige-Gas-Furnace.jpg"
  },
  {
    id: "rheem-r96v-40000-two",
    manufacturer: "Rheem",
    model: "R96V-40000",
    price: 2559,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 40000,
    heatingCapacityBtu: 32000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.8,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/gas-furnaces/r96v/R96V-Prestige-Gas-Furnace.jpg"
  },
  {
    id: "rheem-r96v-40000-variable",
    manufacturer: "Rheem",
    model: "R96V-40000",
    price: 2683,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 40000,
    heatingCapacityBtu: 32000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.8,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/gas-furnaces/r96v/R96V-Prestige-Gas-Furnace.jpg"
  },
  {
    id: "rheem-r80t-50000-single",
    manufacturer: "Rheem",
    model: "R80T-50000",
    price: 3386,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 50000,
    heatingCapacityBtu: 46000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.92,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/gas-furnaces/r80t/R80T-Classic-Plus-Gas-Furnace.jpg"
  },
  {
    id: "rheem-r80t-50000-two",
    manufacturer: "Rheem",
    model: "R80T-50000",
    price: 3351,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 50000,
    heatingCapacityBtu: 46000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.92,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/gas-furnaces/r80t/R80T-Classic-Plus-Gas-Furnace.jpg"
  },
  {
    id: "rheem-r80t-50000-variable",
    manufacturer: "Rheem",
    model: "R80T-50000",
    price: 3074,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 50000,
    heatingCapacityBtu: 46000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.92,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/gas-furnaces/r80t/R80T-Classic-Plus-Gas-Furnace.jpg"
  },
  {
    id: "rheem-r92p-60000-single",
    manufacturer: "Rheem",
    model: "R92P-60000",
    price: 3710,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 60000,
    heatingCapacityBtu: 57600,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.96,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/gas-furnaces/r92p/R92P-Prestige-High-Efficiency-Gas-Furnace.jpg"
  },
  {
    id: "rheem-r92p-60000-two",
    manufacturer: "Rheem",
    model: "R92P-60000",
    price: 3605,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 60000,
    heatingCapacityBtu: 57600,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.96,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/gas-furnaces/r92p/R92P-Prestige-High-Efficiency-Gas-Furnace.jpg"
  },
  {
    id: "rheem-r92p-60000-variable",
    manufacturer: "Rheem",
    model: "R92P-60000",
    price: 3635,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 60000,
    heatingCapacityBtu: 57600,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.96,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/gas-furnaces/r92p/R92P-Prestige-High-Efficiency-Gas-Furnace.jpg"
  },
  {
    id: "rheem-r96v-80000-single",
    manufacturer: "Rheem",
    model: "R96V-80000",
    price: 4332,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 80000,
    heatingCapacityBtu: 77600,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.97,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/gas-furnaces/r96v/R96V-Prestige-Gas-Furnace.jpg"
  },
  {
    id: "rheem-r96v-80000-two",
    manufacturer: "Rheem",
    model: "R96V-80000",
    price: 4351,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 80000,
    heatingCapacityBtu: 77600,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.97,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/gas-furnaces/r96v/R96V-Prestige-Gas-Furnace.jpg"
  },
  {
    id: "rheem-r96v-80000-variable",
    manufacturer: "Rheem",
    model: "R96V-80000",
    price: 4503,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 80000,
    heatingCapacityBtu: 77600,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.97,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/gas-furnaces/r96v/R96V-Prestige-Gas-Furnace.jpg"
  },
  {
    id: "rheem-r80t-100000-single",
    manufacturer: "Rheem",
    model: "R80T-100000",
    price: 5252,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 100000,
    heatingCapacityBtu: 98000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.98,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/gas-furnaces/r80t/R80T-Classic-Plus-Gas-Furnace.jpg"
  },
  {
    id: "rheem-r80t-100000-two",
    manufacturer: "Rheem",
    model: "R80T-100000",
    price: 5070,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 100000,
    heatingCapacityBtu: 98000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.98,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/gas-furnaces/r80t/R80T-Classic-Plus-Gas-Furnace.jpg"
  },
  {
    id: "rheem-r80t-100000-variable",
    manufacturer: "Rheem",
    model: "R80T-100000",
    price: 5227,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 100000,
    heatingCapacityBtu: 98000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.98,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/gas-furnaces/r80t/R80T-Classic-Plus-Gas-Furnace.jpg"
  },
  {
    id: "rheem-r92p-120000-single",
    manufacturer: "Rheem",
    model: "R92P-120000",
    price: 5896,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 120000,
    heatingCapacityBtu: 96000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.8,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/gas-furnaces/r92p/R92P-Prestige-High-Efficiency-Gas-Furnace.jpg"
  },
  {
    id: "rheem-r92p-120000-two",
    manufacturer: "Rheem",
    model: "R92P-120000",
    price: 6121,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 120000,
    heatingCapacityBtu: 96000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.8,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/gas-furnaces/r92p/R92P-Prestige-High-Efficiency-Gas-Furnace.jpg"
  },
  {
    id: "rheem-r92p-120000-variable",
    manufacturer: "Rheem",
    model: "R92P-120000",
    price: 6140,
    isActive: true,
    equipmentType: "furnace",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "indoor",
    systemFunction: "heating",
    nominalTons: null,
    nominalBtu: 120000,
    heatingCapacityBtu: 96000,
    coolingCapacityBtu: null,
    latentCoolingBtu: null,
    afue: 0.8,
    seer: null,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/gas-furnaces/r92p/R92P-Prestige-High-Efficiency-Gas-Furnace.jpg"
  },

  // RHEEM AIR CONDITIONERS  
  {
    id: "rheem-ra20015-single",
    manufacturer: "Rheem",
    model: "RA20015",
    price: 2931,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 1.5,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 18000,
    latentCoolingBtu: 5940,
    afue: null,
    seer: 14,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/air-conditioners/ra20/RA20-Value-Series-Air-Conditioner.jpg"
  },
  {
    id: "rheem-ra20015-two",
    manufacturer: "Rheem",
    model: "RA20015",
    price: 2665,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 1.5,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 18000,
    latentCoolingBtu: 5940,
    afue: null,
    seer: 14,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/air-conditioners/ra20/RA20-Value-Series-Air-Conditioner.jpg"
  },
  {
    id: "rheem-ra20015-variable",
    manufacturer: "Rheem",
    model: "RA20015",
    price: 2942,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 1.5,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 18000,
    latentCoolingBtu: 5940,
    afue: null,
    seer: 14,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/air-conditioners/ra20/RA20-Value-Series-Air-Conditioner.jpg"
  },
  {
    id: "rheem-ra16020-single",
    manufacturer: "Rheem",
    model: "RA16020",
    price: 3561,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 2,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 24000,
    latentCoolingBtu: 7920,
    afue: null,
    seer: 15,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/air-conditioners/ra16/RA16-Classic-Series-Air-Conditioner.jpg"
  },
  {
    id: "rheem-ra16020-two",
    manufacturer: "Rheem",
    model: "RA16020",
    price: 3532,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 2,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 24000,
    latentCoolingBtu: 7920,
    afue: null,
    seer: 15,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/air-conditioners/ra16/RA16-Classic-Series-Air-Conditioner.jpg"
  },
  {
    id: "rheem-ra16020-variable",
    manufacturer: "Rheem",
    model: "RA16020",
    price: 3365,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 2,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 24000,
    latentCoolingBtu: 7920,
    afue: null,
    seer: 15,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/air-conditioners/ra16/RA16-Classic-Series-Air-Conditioner.jpg"
  },
  {
    id: "rheem-ra14025-single",
    manufacturer: "Rheem",
    model: "RA14025",
    price: 4223,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 2.5,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 30000,
    latentCoolingBtu: 9900,
    afue: null,
    seer: 16,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/air-conditioners/ra14/RA14-Classic-Plus-Air-Conditioner.jpg"
  },
  {
    id: "rheem-ra14025-two",
    manufacturer: "Rheem",
    model: "RA14025",
    price: 4102,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 2.5,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 30000,
    latentCoolingBtu: 9900,
    afue: null,
    seer: 16,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/air-conditioners/ra14/RA14-Classic-Plus-Air-Conditioner.jpg"
  },
  {
    id: "rheem-ra14025-variable",
    manufacturer: "Rheem",
    model: "RA14025",
    price: 3914,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 2.5,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 30000,
    latentCoolingBtu: 9900,
    afue: null,
    seer: 16,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/air-conditioners/ra14/RA14-Classic-Plus-Air-Conditioner.jpg"
  },
  {
    id: "rheem-ra20030-single",
    manufacturer: "Rheem",
    model: "RA20030",
    price: 4846,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 3,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 36000,
    latentCoolingBtu: 11880,
    afue: null,
    seer: 17,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/air-conditioners/ra20/RA20-Value-Series-Air-Conditioner.jpg"
  },
  {
    id: "rheem-ra20030-two",
    manufacturer: "Rheem",
    model: "RA20030",
    price: 4868,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 3,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 36000,
    latentCoolingBtu: 11880,
    afue: null,
    seer: 17,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/air-conditioners/ra20/RA20-Value-Series-Air-Conditioner.jpg"
  },
  {
    id: "rheem-ra20030-variable",
    manufacturer: "Rheem",
    model: "RA20030",
    price: 4838,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 3,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 36000,
    latentCoolingBtu: 11880,
    afue: null,
    seer: 17,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/air-conditioners/ra20/RA20-Value-Series-Air-Conditioner.jpg"
  },
  {
    id: "rheem-ra16040-single",
    manufacturer: "Rheem",
    model: "RA16040",
    price: 6110,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 4,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 48000,
    latentCoolingBtu: 15840,
    afue: null,
    seer: 18,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/air-conditioners/ra16/RA16-Classic-Series-Air-Conditioner.jpg"
  },
  {
    id: "rheem-ra16040-two",
    manufacturer: "Rheem",
    model: "RA16040",
    price: 6045,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 4,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 48000,
    latentCoolingBtu: 15840,
    afue: null,
    seer: 18,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/air-conditioners/ra16/RA16-Classic-Series-Air-Conditioner.jpg"
  },
  {
    id: "rheem-ra16040-variable",
    manufacturer: "Rheem",
    model: "RA16040",
    price: 6105,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 4,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 48000,
    latentCoolingBtu: 15840,
    afue: null,
    seer: 18,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/air-conditioners/ra16/RA16-Classic-Series-Air-Conditioner.jpg"
  },
  {
    id: "rheem-ra14050-single",
    manufacturer: "Rheem",
    model: "RA14050",
    price: 7301,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 5,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 60000,
    latentCoolingBtu: 19800,
    afue: null,
    seer: 20,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/air-conditioners/ra14/RA14-Classic-Plus-Air-Conditioner.jpg"
  },
  {
    id: "rheem-ra14050-two",
    manufacturer: "Rheem",
    model: "RA14050",
    price: 7652,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 5,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 60000,
    latentCoolingBtu: 19800,
    afue: null,
    seer: 20,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/air-conditioners/ra14/RA14-Classic-Plus-Air-Conditioner.jpg"
  },
  {
    id: "rheem-ra14050-variable",
    manufacturer: "Rheem",
    model: "RA14050",
    price: 7660,
    isActive: true,
    equipmentType: "ac",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "outdoor",
    systemFunction: "cooling",
    nominalTons: 5,
    nominalBtu: null,
    heatingCapacityBtu: null,
    coolingCapacityBtu: 60000,
    latentCoolingBtu: 19800,
    afue: null,
    seer: 20,
    hspf: null,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/air-conditioners/ra14/RA14-Classic-Plus-Air-Conditioner.jpg"
  },

  // RHEEM HEAT PUMPS
  {
    id: "rheem-rp16015-single",
    manufacturer: "Rheem",
    model: "RP16015",
    price: 3323,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 1.5,
    nominalBtu: null,
    heatingCapacityBtu: 16560,
    coolingCapacityBtu: 18000,
    latentCoolingBtu: 5940,
    afue: null,
    seer: 14,
    hspf: 8.2,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/heat-pumps/rp16/RP16-Classic-Series-Heat-Pump.jpg"
  },
  {
    id: "rheem-rp16015-two",
    manufacturer: "Rheem",
    model: "RP16015",
    price: 3233,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 1.5,
    nominalBtu: null,
    heatingCapacityBtu: 16560,
    coolingCapacityBtu: 18000,
    latentCoolingBtu: 5940,
    afue: null,
    seer: 14,
    hspf: 8.2,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/heat-pumps/rp16/RP16-Classic-Series-Heat-Pump.jpg"
  },
  {
    id: "rheem-rp16015-variable",
    manufacturer: "Rheem",
    model: "RP16015",
    price: 3361,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 1.5,
    nominalBtu: null,
    heatingCapacityBtu: 16560,
    coolingCapacityBtu: 18000,
    latentCoolingBtu: 5940,
    afue: null,
    seer: 14,
    hspf: 8.2,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/heat-pumps/rp16/RP16-Classic-Series-Heat-Pump.jpg"
  },
  {
    id: "rheem-rp14020-single",
    manufacturer: "Rheem",
    model: "RP14020",
    price: 3795,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 2,
    nominalBtu: null,
    heatingCapacityBtu: 22080,
    coolingCapacityBtu: 24000,
    latentCoolingBtu: 7920,
    afue: null,
    seer: 15,
    hspf: 8.5,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/heat-pumps/rp14/RP14-Classic-Plus-Heat-Pump.jpg"
  },
  {
    id: "rheem-rp14020-two",
    manufacturer: "Rheem",
    model: "RP14020",
    price: 3758,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 2,
    nominalBtu: null,
    heatingCapacityBtu: 22080,
    coolingCapacityBtu: 24000,
    latentCoolingBtu: 7920,
    afue: null,
    seer: 15,
    hspf: 8.5,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/heat-pumps/rp14/RP14-Classic-Plus-Heat-Pump.jpg"
  },
  {
    id: "rheem-rp14020-variable",
    manufacturer: "Rheem",
    model: "RP14020",
    price: 3788,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 2,
    nominalBtu: null,
    heatingCapacityBtu: 22080,
    coolingCapacityBtu: 24000,
    latentCoolingBtu: 7920,
    afue: null,
    seer: 15,
    hspf: 8.5,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/heat-pumps/rp14/RP14-Classic-Plus-Heat-Pump.jpg"
  },
  {
    id: "rheem-rp20025-single",
    manufacturer: "Rheem",
    model: "RP20025",
    price: 4744,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 2.5,
    nominalBtu: null,
    heatingCapacityBtu: 27600,
    coolingCapacityBtu: 30000,
    latentCoolingBtu: 9900,
    afue: null,
    seer: 16,
    hspf: 9,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/heat-pumps/rp20/RP20-Value-Series-Heat-Pump.jpg"
  },
  {
    id: "rheem-rp20025-two",
    manufacturer: "Rheem",
    model: "RP20025",
    price: 4790,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 2.5,
    nominalBtu: null,
    heatingCapacityBtu: 27600,
    coolingCapacityBtu: 30000,
    latentCoolingBtu: 9900,
    afue: null,
    seer: 16,
    hspf: 9,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/heat-pumps/rp20/RP20-Value-Series-Heat-Pump.jpg"
  },
  {
    id: "rheem-rp20025-variable",
    manufacturer: "Rheem",
    model: "RP20025",
    price: 4787,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 2.5,
    nominalBtu: null,
    heatingCapacityBtu: 27600,
    coolingCapacityBtu: 30000,
    latentCoolingBtu: 9900,
    afue: null,
    seer: 16,
    hspf: 9,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/heat-pumps/rp20/RP20-Value-Series-Heat-Pump.jpg"
  },
  {
    id: "rheem-rp16030-single",
    manufacturer: "Rheem",
    model: "RP16030",
    price: 5521,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 3,
    nominalBtu: null,
    heatingCapacityBtu: 33120,
    coolingCapacityBtu: 36000,
    latentCoolingBtu: 11880,
    afue: null,
    seer: 17,
    hspf: 9.5,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/heat-pumps/rp16/RP16-Classic-Series-Heat-Pump.jpg"
  },
  {
    id: "rheem-rp16030-two",
    manufacturer: "Rheem",
    model: "RP16030",
    price: 5373,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 3,
    nominalBtu: null,
    heatingCapacityBtu: 33120,
    coolingCapacityBtu: 36000,
    latentCoolingBtu: 11880,
    afue: null,
    seer: 17,
    hspf: 9.5,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/heat-pumps/rp16/RP16-Classic-Series-Heat-Pump.jpg"
  },
  {
    id: "rheem-rp16030-variable",
    manufacturer: "Rheem",
    model: "RP16030",
    price: 5373,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 3,
    nominalBtu: null,
    heatingCapacityBtu: 33120,
    coolingCapacityBtu: 36000,
    latentCoolingBtu: 11880,
    afue: null,
    seer: 17,
    hspf: 9.5,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/heat-pumps/rp16/RP16-Classic-Series-Heat-Pump.jpg"
  },
  {
    id: "rheem-rp14040-single",
    manufacturer: "Rheem",
    model: "RP14040",
    price: 6692,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 4,
    nominalBtu: null,
    heatingCapacityBtu: 44160,
    coolingCapacityBtu: 48000,
    latentCoolingBtu: 15840,
    afue: null,
    seer: 18,
    hspf: 10,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/heat-pumps/rp14/RP14-Classic-Plus-Heat-Pump.jpg"
  },
  {
    id: "rheem-rp14040-two",
    manufacturer: "Rheem",
    model: "RP14040",
    price: 6709,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 4,
    nominalBtu: null,
    heatingCapacityBtu: 44160,
    coolingCapacityBtu: 48000,
    latentCoolingBtu: 15840,
    afue: null,
    seer: 18,
    hspf: 10,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/heat-pumps/rp14/RP14-Classic-Plus-Heat-Pump.jpg"
  },
  {
    id: "rheem-rp14040-variable",
    manufacturer: "Rheem",
    model: "RP14040",
    price: 6952,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 4,
    nominalBtu: null,
    heatingCapacityBtu: 44160,
    coolingCapacityBtu: 48000,
    latentCoolingBtu: 15840,
    afue: null,
    seer: 18,
    hspf: 10,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/heat-pumps/rp14/RP14-Classic-Plus-Heat-Pump.jpg"
  },
  {
    id: "rheem-rp20050-single",
    manufacturer: "Rheem",
    model: "RP20050",
    price: 8332,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "single_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 5,
    nominalBtu: null,
    heatingCapacityBtu: 55200,
    coolingCapacityBtu: 60000,
    latentCoolingBtu: 19800,
    afue: null,
    seer: 20,
    hspf: 10.5,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/heat-pumps/rp20/RP20-Value-Series-Heat-Pump.jpg"
  },
  {
    id: "rheem-rp20050-two",
    manufacturer: "Rheem",
    model: "RP20050",
    price: 8065,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "two_stage",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 5,
    nominalBtu: null,
    heatingCapacityBtu: 55200,
    coolingCapacityBtu: 60000,
    latentCoolingBtu: 19800,
    afue: null,
    seer: 20,
    hspf: 10.5,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/heat-pumps/rp20/RP20-Value-Series-Heat-Pump.jpg"
  },
  {
    id: "rheem-rp20050-variable",
    manufacturer: "Rheem",
    model: "RP20050",
    price: 8068,
    isActive: true,
    equipmentType: "heat_pump",
    distributionType: "ducted",
    staging: "variable_speed",
    unitLocation: "split_system",
    systemFunction: "heating_cooling",
    nominalTons: 5,
    nominalBtu: null,
    heatingCapacityBtu: 55200,
    coolingCapacityBtu: 60000,
    latentCoolingBtu: 19800,
    afue: null,
    seer: 20,
    hspf: 10.5,
    cabinetWidth: null,
    cabinetHeight: null,
    cabinetDepth: null,
    imageUrl: "https://www.rheem.com/content/dam/Rheem/North%20America/products/residential/heat-pumps/rp20/RP20-Value-Series-Heat-Pump.jpg"
  }
];